#!/usr/bin/env bash
#
# bootstrap-new-repo.sh — push the extracted branch to debrief/spec-navigator
# as main, drop in CI workflows + docs, and prepare the patch queue.
#
# Run AFTER extract.sh (which produces the extracted branch) and AFTER you have
# created the empty repository on github.com.
#
# Usage:
#   ./bootstrap-new-repo.sh [extracted-clone-dir]
#
# Defaults to /tmp/spec-navigator-extract (matching extract.sh's default).

set -euo pipefail

EXTRACT_DIR="${1:-/tmp/spec-navigator-extract}"
NEW_REMOTE="git@github.com:debrief/spec-navigator.git"
EXTRACT_BRANCH="spec-navigator-extracted"
KIT_DIR="$(cd "$(dirname "$0")/.." && pwd)"

echo "==> spec-navigator extraction kit / Step 3: bootstrap new repo"
echo "    Extracted clone: ${EXTRACT_DIR}"
echo "    New remote:      ${NEW_REMOTE}"
echo "    Kit directory:   ${KIT_DIR}"
echo

if ! [[ -d "${EXTRACT_DIR}/.git" ]]; then
  echo "ERROR: ${EXTRACT_DIR} is not a git working tree."
  echo "       Run extract.sh first."
  exit 1
fi

cd "${EXTRACT_DIR}"

if ! git rev-parse --verify "${EXTRACT_BRANCH}" >/dev/null 2>&1; then
  echo "ERROR: branch ${EXTRACT_BRANCH} not present in ${EXTRACT_DIR}."
  echo "       Run extract.sh first."
  exit 1
fi

git switch "${EXTRACT_BRANCH}"

# --- Push as main ---------------------------------------------------------

echo "==> Adding remote (idempotent)."
if git remote | grep -q '^new-repo$'; then
  git remote set-url new-repo "${NEW_REMOTE}"
else
  git remote add new-repo "${NEW_REMOTE}"
fi

echo "==> Pushing ${EXTRACT_BRANCH} to new-repo:main."
echo "    If this fails because the remote rejects the push (non-empty repo),"
echo "    delete the remote repo, recreate it empty, and re-run."
git push new-repo "${EXTRACT_BRANCH}:main"

# --- Drop in CI workflows -------------------------------------------------

echo "==> Installing CI workflows."
mkdir -p .github/workflows
cp "${KIT_DIR}/workflows/ci.yml"     .github/workflows/ci.yml
cp "${KIT_DIR}/workflows/live.yml"   .github/workflows/live.yml
cp "${KIT_DIR}/workflows/deploy.yml" .github/workflows/deploy.yml

# --- Drop in docs ---------------------------------------------------------

echo "==> Installing README, CONFIGURATION, SECURITY."
cp "${KIT_DIR}/templates/README.md"        README.md
cp "${KIT_DIR}/templates/CONFIGURATION.md" CONFIGURATION.md
cp "${KIT_DIR}/templates/SECURITY.md"      SECURITY.md

# --- Walk the patches interactively --------------------------------------

cat <<'EOF'

==> Patch queue.

Each file under patches/ is a self-contained recipe describing a code change
that has to land on the extracted branch BEFORE the first deploy. They are
recipes (not literal patch files) because some involve new files whose content
depends on the extracted source layout.

Apply them now in order:

    patches/01-vite-base-default.md       (one-line edit to vite.config.ts)
    patches/02-url-compat-shim.md         (legacy ?pr= resolver)
    patches/03-bundled-fixtures.md        (e2e/fixtures/ + Playwright wiring)
    patches/04-eslint-standalone.md       (replace monorepo eslint extends)
    patches/05-tsconfig-standalone.md     (replace tsconfig extends)

Open each file, follow the recipe, commit each as a separate commit on the
extract branch. After all five are committed, push:

    git push new-repo main

EOF

# --- Commit the workflows + docs as a single starter commit --------------

echo "==> Staging workflows + docs for a single bootstrap commit."
git add .github/workflows/ README.md CONFIGURATION.md SECURITY.md
git -c user.email="extraction-kit@debrief.local" \
    -c user.name="spec-navigator extraction kit" \
    commit -m "chore: install CI workflows and adopter-facing docs

Generated by debrief-future:specs/248-extract-spec-navigator/extraction-kit/.
See ../../debrief-future spec dir for context." || \
    echo "    (no changes to commit — already bootstrapped)"

cat <<EOF

==> Bootstrap commit prepared on local ${EXTRACT_BRANCH}.

Next steps (in order):

  4. Apply each file under ${KIT_DIR}/patches/ to this branch, committing
     each separately. Then:

       git push new-repo ${EXTRACT_BRANCH}:main

  5. Enable GitHub Pages: gh api -X POST repos/debrief/spec-navigator/pages \\
       -f build_type=workflow

  6. Register the live-mode PAT:
       gh secret set GITHUB_TOKEN --repo debrief/spec-navigator --body "<your-PAT>"

  7. Trigger the first deploy:
       gh workflow run deploy.yml --repo debrief/spec-navigator --ref main

  8. Smoke-test the four URL forms documented in README.md.

EOF
