/**
 * Contract: provenance entry shape written by stacService.updateItemMetadata
 * into item.properties["debrief:provenance_log"].
 *
 * This is the TypeScript mirror of the LinkML class PropertiesProvenanceEntry
 * (defined in shared/schemas/src/linkml/stac-extension.yaml). At generation
 * time, the LinkML → TypeScript pipeline produces the canonical type and
 * consumers import it from @debrief/schemas. This contract file exists to pin
 * the shape during spec/review and to document the write-time invariants
 * enforced by the service.
 *
 * Decision 7 (post-review): Item-level provenance lives on item.properties
 * as its own array. LogService.recordToolResult is NOT used for these entries
 * (that method's used[] field is interpreted as feature IDs and would
 * misroute).
 */

export const PROPERTIES_PANEL_TOOL_SENTINEL = 'debrief.propertiesPanel' as const;

export interface PropertiesProvenanceEntry {
  /**
   * ULID — unique per commit. Generated by the service writer, not the
   * webview. Consumers (replay, undo, cross-referencing with LogPanel) rely
   * on this being monotonically sortable.
   */
  activity_id: string;

  /**
   * ISO-8601 UTC, set by the service at write time. MUST NOT be backfilled
   * by the caller — the writer is the single source of truth for write time.
   */
  timestamp: string;

  /** Sentinel identifying the Properties Panel as the writer. */
  tool: typeof PROPERTIES_PANEL_TOOL_SENTINEL;

  /**
   * Versioned method name, e.g. 'properties-panel@1.0.0'. Populated from the
   * @debrief/components package.json version so replays can identify which
   * UI version produced the edit.
   */
  method: `properties-panel@${string}`;

  /**
   * List of field names (keys on item.properties) that the analyst touched
   * in this single commit. MUST be length ≥ 1 — an empty commit is a no-op
   * and MUST NOT produce an entry. Order MUST be stable (sorted) for
   * deterministic replay.
   */
  fields: string[];

  /** Always 'user' for Properties Panel entries — edits are human-initiated. */
  source: 'user';
}

/**
 * Test-facing invariant. Use this as a predicate in integration tests that
 * inspect item.properties["debrief:provenance_log"] after a commit.
 */
export function isValidPropertiesProvenanceEntry(
  entry: unknown,
): entry is PropertiesProvenanceEntry {
  if (typeof entry !== 'object' || entry === null) return false;
  const e = entry as Record<string, unknown>;
  return (
    typeof e.activity_id === 'string' &&
    e.activity_id.length > 0 &&
    typeof e.timestamp === 'string' &&
    e.tool === PROPERTIES_PANEL_TOOL_SENTINEL &&
    typeof e.method === 'string' &&
    e.method.startsWith('properties-panel@') &&
    Array.isArray(e.fields) &&
    (e.fields as unknown[]).length >= 1 &&
    (e.fields as unknown[]).every((v) => typeof v === 'string') &&
    e.source === 'user'
  );
}

/**
 * Archive file invariants — enforced by stacService when rotating entries out
 * of item.properties["debrief:provenance_log"] into
 * <item_dir>/provenance_log_archive.jsonl. One JSON-serialised entry per
 * line, append-only, atomic append (temp+rename).
 */
export const PROVENANCE_LOG_CAP = 500 as const;
export const PROVENANCE_LOG_ARCHIVE_FILENAME = 'provenance_log_archive.jsonl' as const;
