/**
 * Provenance entry shape + archive constants shared between webview and
 * extension-side stacService. Mirrors the LinkML class
 * PropertiesProvenanceEntry (see shared/schemas/src/linkml/stac-extension.yaml).
 */

export const PROPERTIES_PANEL_TOOL_SENTINEL = 'debrief.propertiesPanel' as const;

export interface PropertiesProvenanceEntry {
  /** ULID — monotonically sortable, generated by the service at write time. */
  activity_id: string;
  /** ISO-8601 UTC timestamp set by the service at write time. */
  timestamp: string;
  /** Sentinel identifying the Properties Panel as the writer. */
  tool: typeof PROPERTIES_PANEL_TOOL_SENTINEL;
  /** Versioned method identifier, e.g. `properties-panel@1.0.0`. */
  method: `properties-panel@${string}`;
  /** Non-empty sorted list of field names touched in this commit. */
  fields: string[];
  /** Always 'user' for Properties Panel entries. */
  source: 'user';
}

/**
 * Runtime predicate used by integration tests to verify a written entry
 * satisfies the contract.
 */
export function isValidPropertiesProvenanceEntry(
  entry: unknown,
): entry is PropertiesProvenanceEntry {
  if (typeof entry !== 'object' || entry === null) return false;
  const e = entry as Record<string, unknown>;
  return (
    typeof e.activity_id === 'string' &&
    e.activity_id.length > 0 &&
    typeof e.timestamp === 'string' &&
    e.tool === PROPERTIES_PANEL_TOOL_SENTINEL &&
    typeof e.method === 'string' &&
    (e.method as string).startsWith('properties-panel@') &&
    Array.isArray(e.fields) &&
    (e.fields as unknown[]).length >= 1 &&
    (e.fields as unknown[]).every((v) => typeof v === 'string') &&
    e.source === 'user'
  );
}

/** Max entries retained on `item.properties["debrief:provenance_log"]`. */
export const PROVENANCE_LOG_CAP = 500 as const;

/** Sibling JSONL archive for rotated entries. */
export const PROVENANCE_LOG_ARCHIVE_FILENAME = 'provenance_log_archive.jsonl' as const;
