/**
 * Viewport signal detection constants.
 * Feature: 089-result-auto-refresh (E04)
 *
 * Well-known Vega signal prefixes that indicate interactive viewport state.
 * These are the signals generated by Vega-Lite's selection parameters
 * with type "interval" (used for zoom/pan).
 */

export const VIEWPORT_SIGNAL_PREFIXES = [
  'brush_',     // Default interval selection
  'zoom_',      // Zoom interaction
  'pan_',       // Pan interaction
  'grid_',      // Grid selection (bidirectional zoom)
  'x_',         // X-axis domain override
  'y_',         // Y-axis domain override
] as const;
